
---
version: '3.4'

services:
  resque-web-wrapper:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    - .:/resque-web-wrapper
    ports:
    - "3000:3000"
    depends_on:
    - redis
    environment:
    - RAILS_RESQUE_REDIS=redis
    - RAILS_RESQUE_REDIS_NAMESPACE=development:gizmo
  redis:
    image: redis:3.2.5

